name: Build Neptune Installer

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Build Installer
        run: go build -o neptune-installer.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: neptune-installer
          path: neptune-installer.exe
